import { type NextPage } from "next";
import Head from "next/head";
import Card from "@/components/Card";
import { api } from "@/utils/api";
import DashboardOptions from "@/components/DashboardOptions";

const Home: NextPage = () => {
  const cardsQuery = api.cards.getAll.useQuery();

  async function onCardAdded() {
    await cardsQuery.refetch();
  }

  return (
    <>
      <Head>
        <title>Dashboard - QuickLinks</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <div className="container flex flex-col items-center justify-center gap-8 px-4 py-16">
          <div className="w-full">
            <h1 className="w-full text-4xl font-extrabold tracking-tight">
              QuickLinks
            </h1>
            <div className="flex flex-row items-start gap-2">
              <h2 className="text-2xl">Dashboard</h2>
              <DashboardOptions onCardAdded={onCardAdded} />
            </div>
          </div>
          <div className="grid w-full grid-cols-6 gap-16">
            {cardsQuery.data?.map((card, i) => (
              <Card key={i} card={card} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
